
TOKEN = "5719458669:AAGeCICW3moB5m2qpj4YMh_67Kx7HpgWIqg"
MYSQL_USER = "root"
MYSQL_PASSWORD = "qwer12"
MYSQL_DATABASE = "emoji_db"
MYSQL_HOST = "localhost"


MYSQL_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}"



REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379

